### ISSUE TITLE
Photography Equipment

### ISSUE THREAD

**Issue by ChrSteinert** [Krzysztof-Cieslak/AMA#14]
What do you like about your current photography equipment (Canon 5D Mark III ?) and what equipment to you plan to buy next and why?

**Comment by Krzysztof-Cieslak** [comment]
So... the equipment:
* Canon 5D Mark III - it's just good overall body, bit a "jack of all trades"  - good image quality, decent dynamic range, good performance in low light, decent high ISO quality, good autofocus when using Canon's L lenses (well, that's kind of obvious). I love it's full frame - I've started photography back in the times of 35 mm film, and while smaller sensors allow taking great pictures I was always missing characteristic of full frame on the other digital cameras I had before 5D3.
* Canon 24-105mm L F/4.0 IS - my first Canon lens, I've got it with the previous body I had (50D). OK travel lens. Decent image quality, decent stabilizer. Not using it at all nowadays, have better options - I'm leaving for the vacations tomorrow and it stays at home.
* Canon 70-200mm L F/4.0 IS - really good telelens, not super expensive. I'd recommend it for everyone. Can do portraits, sometimes sports, really good for landscape. Not as good as 70-200 L 2.8 IS... but half as expensive, and half as heavy ;)
* Canon 50mm L F/1.2 - my favorite lens, standard, amazing image quality. It's my go-to lens nowadays. Great for almost anything - portraits, landscapes, street, traveling. I just love it. The only drawback is that it's really hard to hit sharpness well on 1.2 ;)
* Canon 24mm L F/1.4 - great prime lens, great image quality. I like it for traveling and sightseeing - 50mm is often not wide enough to do some quick snapshots from the sightseeing. Good for architecture (but you need to be careful about distortion ), great for landscapes. Together with 50mm creates my basic setup I take when I'm traveling and I can't take all equipment.
* Lee Filters 150Mk2 "Big Stopper"  - it's full gray ,10 stops filter for long exposure photography. I've only got it recently and haven't played too much with it. I hope I can tell more after vacations
* Lee Filters 150Mk2 0.6ND Hard Grad - graduated (half gray, half neutral) 2 stops filter for landscape photography. As with Big Stopper just bought it, more opinions after vacations.

+ bunch of other equipment (tripod, UV filter for each lens for protection, remote controller, polarization filter 77mm (fits 24-105 and 50 lenses) )

What next?

Probably couple of more Lee FIlters if I'm happy with those 2 I have. Other than that? Maybe Canon 100mm L F/2.8 IS Macro - to do some macro photography ;).  But it's not something I plan to get soon.

Also I feel that I have way to much equipment and spend not enough time on photography - I travel quite a lot (work + conferences) to many interesting places but I rarely have enough time to do any "real" photography - it's usually day or half of sightseeing, taking some random snapshots. I plan spending some money on traveling dedicated to photography instead of buying even more equipment.
