### ISSUE TITLE
 📸

### ISSUE THREAD

**Issue by coolya** [Krzysztof-Cieslak/AMA#15]
would you consider photography a hobby, a passion or just some distraction from coding for you?

When did you start with it?

**Comment by Krzysztof-Cieslak** [comment]
It's definitely passion for me. Unfortunately, one I'm not spending enough time on.

It's bit hard to tell when I've started because it's also my father's hobby and the photography was always in my live. So I've learned basics when I was rather young. I've got my first digital camera when I was 13 or 14, I've had 2 simple film cameras before that
