### ISSUE TITLE
How did you get started in the consulting business

### ISSUE THREAD

**Issue by 0x53A** [Krzysztof-Cieslak/AMA#24]
Normally you hear a lot of bad rap about consultants in general.
I find it amazing how there are F# consultancies which do produce high quality open source.

Just from the top of my mind:

* you, LAMBDA FACTORY -> Ionide
* Nessos -> MBrace
* Compositional-IT -> Azure Stuff

This is not meant to be exhaustive ;-)

Since this AMA is about you I would rather like to know how you got started with consulting (and F#), instead of asking a pointless question how F# is dying (again).

**Comment by Krzysztof-Cieslak** [comment]
I've first heard about F# around 2010, I was on some conference in my home town, and there was talk about it (that was time of F# 2.0, when it first got included in VS). I've thought it was interesting language, I've tried to learn it, I've failed miserably and went back to C# ;) But I was paying attention to some news around F# to just make sure I'm not missing new hype train ;)
 
Some years later (2013, I think) I was on student exchange in Denmark and I had "Introduction to FP" course which used F#, and since then I've been using it for some personal hacking and just practicing. 
In January 2015 I attended Lambda Days conference where I've meet couple of members of F# Community including Andrea, Evelina and Tomas what made me fall in love with F# Community. 
Around this time I was also getting to know basics of OSS movement (reading `The Cathedral and the Bazaar` and some Pieter Hintjens' works). Both those 2 things together + fact I've enjoyed Atom for other programming languages were reasons to start Ionide in March 2015. 

I've started consulting business year later - in January 2016. I was already pretty well recognized inside F# Community (due to raising popularity of Ionide). And it happened kinda by accident / luck - my contract in the company I've been working on (C# shop) was ending and I've tweeted that I'm looking for new job, and it would be cool if it was F#. Luckily I was contacted by company from Vancouver which decided to build new system in F#, they haven't got any experience with F# and were looking for someone who could help them write system and additionally do bit of mentoring / internal training to introduce F# to the team. 

So in my case it was more Ionide driving forward Lambda Factory than other way round... especially in early days of my F# career.
