### ISSUE TITLE
What are the top three features you'd like to see in F#?

### ISSUE THREAD

**Issue by Rickasaurus** [Krzysztof-Cieslak/AMA#27]

**Comment by Krzysztof-Cieslak** [comment]
1. Higher sorted kinds
2. Dependent types 
3. First class optics

;)

TBF, I'm not sure, personally I'm rather happy about the language. Rather than some new big shiny features I'd prefer quality of life changes around TPs, quotations and compiler (FCS) performance. Especially the better FCS performance would be amazing, I had proof of concepts of some really interesting tooling ideas that I've never shown just because they were ridiculously slow.
