### ISSUE TITLE
GitHub vs GitLab

### ISSUE THREAD

**Issue by ChrSteinert** [Krzysztof-Cieslak/AMA#33]
Coming from [this twitter conversation](https://twitter.com/chrsteinert/status/912745318340493312) I am highly interested in your take in the GitHub vs GitLab discussion. 
A lot of your stuff is going on here on GitHub. Yet, Fornax for example is (currently) hosted on GitLab. So why is Fornax there, why other stuff here? What were your experience on either platform and why did you chose to still have the majority on GitHub?

**Comment by Krzysztof-Cieslak** [comment]
Whoops, I've forgotten to answer it.

I do strongly believe that GitLab is the superior technical choice - docker based CI, much better way of publishing documentation, more options for the management, more options for the access management for different parts of the repository.  Not to mention free private repos.

Unfortunately, doing community driven OSS is not about technical choices. It's about removing as many barriers as possible that will stop users from contributing. And familiarity with GitHub and the fact that basically, whole Community is here makes it way easier to drive a project forward, get meaningful discussions and contributions. I can't expect that majority of people will use something they do not know, force them to create an additional account on another portal (even tho, you can log-in with GitHub account). Also, since everyone is here it makes a project more discoverable - about projects I host on GitLab know only people who follow me on Twitter, which is again not great for the growth of the project.
