### ISSUE TITLE
Rider

### ISSUE THREAD

**Issue by vivainio** [Krzysztof-Cieslak/AMA#34]
Do you regularly compare Ionide with Rider?

Since they both use FCS, do you think they will retain parity on basic F# experience, or do you see areas where either Rider or Ionide could pull ahead (apart from the usual IDE usability features).

**Comment by Krzysztof-Cieslak** [comment]
Personally, I don't compare it with Rider or VS at all, I actually don't have any of those IDEs installed on my main machine. However, F# channel in FP Slack is really often a place of the editor tooling discussion (people working on Rider and contributing to VF# hangs out there) so I always get enough feedback (or hype killer, if you prefer ;) ) when I implement something new.

I think JetBrains folks, in general, know more about building editor tooling than me, and they can leverage some common utilities they are famous for (great caching and indexing) so I expect some features in Rider working really well. Also, I'm excited since I hope we will get lot of contributions to FCS from JetBrains which will make all editors better :)

On the other hand, as far as I know, there is only one developer working on F# support in Rider, so I wouldn't expect massive innovation - but a rather level of tooling similar to VS and Ionide. I believe the advantages of Ionide can be better integration with other community-driven tools (Paket, FAKE, Expecto), faster iteration cycle, and general VSCode's UX which lot of people started to like over last year or so. Also, I have some ideas for innovative features but unfortunately I don't really have time to investigate anything new - trying to focus on fixing bugs, keeping up with new .Net stuff, and new VSCode stuff.
