### ISSUE TITLE
Personal Blog - tips & tricks

### ISSUE THREAD

**Issue by fswalker** [Krzysztof-Cieslak/AMA#35]
- What are your recommendations, guidelines, tips, lessons learnt in terms of building and running the blog?
- Do you recommend some technologies, domains, servers, etc. in particular?
- What would you avoid?
- If  you were given *second chance* to build your personal blog, would you do it exactly in the same way and use the same _stuff_?

Thanks! :)

**Comment by Krzysztof-Cieslak** [comment]
TBF, I'm not blogging a lot so not sure if I'm best one to ask about blogging. 

General tips: 

- in general, I do recommend blogging, I guess every developer do something interesting, and while it may seem boring for you (because you spend a lot time on this particular topic) it may be useful for someone else.
 - For the technologies - static site generator + GitHub/GitLab pages. It's really simple to start, things like Jekyll has tones of nice themes (both free and paid) in the internet. Since most of the supports markdown you're not chained to one particular technology - changing it in the future should be fairly simple. 
 - That's not really from my experiance, but some other people I know - blog regurarly if you want to build huge audience quickly. It was never my aim really so I blog when I find something super interesting and have some time to write it (which is problem ;) )
