### ISSUE TITLE
What is the plan for FSharp.Formatting to write generated files?

### ISSUE THREAD

**Issue by jackfoxy** [Krzysztof-Cieslak/AMA#39]
https://github.com/fsprojects/FSharp.Formatting/pull/425 left the master in a state where F#.Formatting no longer writes doc and ref files. It looks like you intended to add a generator to the context passed to Formatting, but were overruled by project maintainer(s).

What is/was the plan to write output files?

**Comment by Krzysztof-Cieslak** [comment]
It was quite a long time ago, and I haven't looked at the F# Formatting much since then.. but I'm pretty sure you can still generate documentation as before. However, there was breaking API change and now previous functionality based on Razor is in its own namespaces. The PR has enabled adding other templating engines than Razor, I was planning to add Fornax, but never got enough time to do it.
