### ISSUE TITLE
Is a hatred of .Net and a love of F# a consistent worldview?

### ISSUE THREAD

**Issue by chillitom** [Krzysztof-Cieslak/AMA#4]
So I've seen you say on a few occasions that you hate _.Net_ yet you clearly love F#.. what is it about .Net that you hate?  Does it detract from your love of F#?

**Comment by Krzysztof-Cieslak** [comment]
If I really hated .Net I'd not waste so much time for it ;)

I like .Net as technical choice - Framework is OK, underlying VM is good. 
I dislike .Net as ecosystem and I dislike .Net community - the one-vendor, everything-by-MS, only-use-stuff-out-of-the-box-in-VS mentality is rampant , general community is weak and doesn't try to fight hard enough, MS is abusing this weakness to control the ecosystem as hard as no other vendor in any other ecosystem I know.

Also, I don't *love* F#. I *like* it - it's really good language, that can use power of .Net which is huge advantage in comparison to let's say OCaml.

What I do love is F# Community - not only because they're productive, OSS focused bunch of folks... but because they're cool people and great friends. 

Also, we now have Fable, I can hate .Net as much as I want ;)
