### ISSUE TITLE
What are your thoughts on paying your bills vs. supporting open source?

### ISSUE THREAD

**Issue by terrajobst** [Krzysztof-Cieslak/AMA#50]
I have the luxury to pursue my passion in working on OSS during my day job, which takes all the risk away from me because I'm employed and get regular pay checks. But I wonder how folks like you who are freelancers strike that balance.

What have you tried and what worked and what didn't?

**Comment by Krzysztof-Cieslak** [comment]
Hey this is great question. 

So I think I have couple of general points regarding that and they all take some part in "deciding" how much time I spend on OSS:

1. I like coding, I like doing OSS, and I like F# community - which means I treat some of the stuff I do as a hobby, and I'm fine with spending my personal time on it, just like I spend it on my other hobbies (like photography)

2. I'm fairly successful with my business (I'm earning decently, I don't have too many problems with finding new clients,  and it's all going well enough that I actually [started to grow the company a bit](https://twitter.com/Lambda_Factory/status/1011594576744808453)) - and in huge part this is thanks to my OSS contributions, and it's pretty clear to me that OSS work is pretty good marketing investment.

3. Some of the work (especially in the web space, things like Saturn, Tennis, or SAFE initiative) are  basically business investments - I invest my time into creating space on the market in which my company can be leader.

4. I usually work with my clients remotely and with flexible work hours which means I'm in the lucky position where I have some flexibility regarding how much I work on the "paid" stuff and how much I spend on OSS. Ofc, this itself is balance act - I need to keep my clients happy, so I can't just say "Oh, I've done nothing for your project in last 2 weeks because I've been building some fun OSS project". But still I'm in the lucky position where I have some decision making power and freedom.

5. I live in Poland, and Poland is not the place with high living cost :-) I can feel OK spending bit less time working because even with charging fewer hours it's still working with companies from US, Canada, UK or Western Europe requiring fairly specialized skillset (FP/F#) and it means I'm earning way more than average software developer in Poland (not to mention average "normal" person)

In the end I'm trying to spend 30-35 hours weekly on "paid" stuff, and 10-20 hours weekly on OSS stuff. It's probably still bit too much - and I really wish that some of the paid stuff were actually my OSS stuff, but I'm not lucky enough yet.

> What have you tried and what worked and what didn't?

* I've tried working way more (30-40 hours weekly) on OSS while working 40 hours weekly on paid stuff... and let's just say this didn't end well, and is not something I'd recommend doing ;-)
* I've tried building [paid project](https://gumroad.com/l/NeptunePlugin) as an "extension" of my OSS project - and this is not working out too well, but I blame the very specific market niche (editor tooling) for it. 
* Right now, as I've mentioned above, I'm trying to do consulting and especially training services around the OSS stuff I do in F# web ecosystem and I feel this is going pretty OK now, and has quite a lot of growth potential.
* I've tried finding sponsoring for working on OSS (i.e. pay me for some small amount of hours of my work I'll spend on OSS focusing on the issues/features you need etc)  from some companies using my stuff and this has failed so far, tho with Saturn I'm actually talking with some people so it may change in the future.

**Comment by jackfoxy** [comment]
Software tools is just not a good market. I learned that in the '90s and had the CEO of a very successful game company explain it to me. Most half-way decent programmers are attracted to writing tools (why? would be a long discussion), and immediately they start thinking "I could sell this".

**Comment by c00kiemon5ter** [comment]
[A New Social Contract for Open Source](https://hueniverse.com/a-new-social-contract-for-open-source-86d1fcf3e353) by @hueniverse was an interesting read on the subject.
