### ISSUE TITLE
Has Forge been deprecated now that FAKE is a dotnet tool?

### ISSUE THREAD

**Issue by nodrogyad** [Krzysztof-Cieslak/AMA#52]
Hi Kris, tried to use the latest Forge today via scoop and discovered it doesn't work with the latest FAKE (5) due to build.fsx issues at a minimum.  Any move afoot to bring it up to speed or is the project dead due to overlap with the dotnet adoption?

**Comment by Krzysztof-Cieslak** [comment]
Hey,

Forge is basically deprecated due to multiple reasons - mostly connected to how .NET evolved with the introduction of `dotnet` CLI tool:

* `dotnet new` does project scaffolding ~better~ in a way that has become standard in .NET community
* `dotnet add reference` works out of the box
* Paket and FAKE works now as dotnet tools and again, it's a standard way of using such tools in .NET community.

Forge is still used in some cases by Ionide (moving files up/down in fsproj) but I'm planning to move those to our language server (FSAC).

I wouldn't recommend using Forge in 2020 - `dotnet` CLI does everything that's necessary for typical development workflow.
