### ISSUE TITLE
Why you hate .NET? What is your favorite stack these days?

### ISSUE THREAD

**Issue by jasiozet** [Krzysztof-Cieslak/AMA#55]

**Comment by Krzysztof-Cieslak** [comment]
### Why do I hate .NET?

Funny fact - nothing has really changed in the last 5 years for me, since I've answered a [similar question](https://github.com/Krzysztof-Cieslak/AMA/issues/4) for the first time here:
This opinion is just as accurate today as it was 5 years ago:

> If I really hated .Net I'd not waste so much time for it ;)
>I like .Net as technical choice - Framework is OK, underlying VM is good.
>I dislike .Net as ecosystem and I dislike .Net community - the one-vendor, everything-by-MS, only-use-stuff-out-of-the- box-in-VS mentality is rampant , general community is weak and doesn't try to fight hard enough, MS is abusing this weakness to control the ecosystem as hard as no other vendor in any other ecosystem I know.

### What is my favourite stack these days?

I don't really think I have one right now - I don't really care about technical choices as long as I can do something meaningful (well, that removes a whole bunch of stacks from the equation, like C#) 

If I were to answer I'd say I mostly enjoy working in stacks that put low technical barriers to unleashing creativity - I want to solve problems, not focus on coding. F# is a pretty decent example of that when I think about experimenting with editor tooling ideas (thanks to FCS). TypeScript (both Node and Web) is also fairly great - technologies like Svelte and SvelteKit are really magical in hiding a lot of technical complexity and allow me to focus on doing cool stuff.

**Comment by jasiozet** [comment]
Thanks for a detailed answer!
