### ISSUE TITLE
How much economy of scale is gained by doing both F# and Elm?

### ISSUE THREAD

**Issue by daxfohl** [Krzysztof-Cieslak/AMA#6]
(disclosure: I've never used Elm beyond tutorials and didn't know you ran that project until just now)

Elm and F# are similar-ish syntax, though very different communities.  Once you've worked through a feature on the Elm side, how much faster does it allow you to do the same feature on the F# side?  Or does it not even come into play much because most "features" only apply to one language (e.g. paket integration)?  How much does the similarity of the syntax of the languages help?

A side question, I'm just curious, why does your F# project support both VSCode and Atom, but Elm only VSCode?  Or actually I guess I could rephrase that as "how much economy of scale is gained by supporting both atom and vscode"?

**Comment by Krzysztof-Cieslak** [comment]
From the language features point of view (like tooltips, autocomplete etc) - there is no advantage coming up from the fact that I'm working on both F# and Elm editor tooling. 
What is important is that I have huge experience with VSCode extension system, UX, etc - what's some kind of advantage for the Elm plugin (which was started later, and is not as feature-complete as Ionide).

Also , if we're on this topic, it's important to notice that in case of F# I'm not only developing plugin, but also contribute a lot FSAC (https://github.com/fsharp/FsAutoComplete), and I know FCS' API reasonably well. In case of Elm plugin - I never has done anything on the compiler / language service projects, I'm not even main developer of VSCode plugin - I just play the role of maintainer / project owner  while most features are developed by contributors from community. 

To the VSCode and Atom - it's similar situation to Elm and F# - nothing is directly gained (the extension APIs are totally different, on different abstraction level, and there are many different architectural choices between those editors), but due to the fact I was doing Atom before VSCode I already had some knowledge about UX, what people expects etc.
Why Elm is only VSCode? Because there already exists great Atom plugin for Elm.
