### ISSUE TITLE
What's your typical day?

### ISSUE THREAD

**Issue by chillitom** [Krzysztof-Cieslak/AMA#9]
How much time do you devote to OSS? How much to work?

What do you do when not coding? (If you're ever not coding)

**Comment by Krzysztof-Cieslak** [comment]
6-7 hours of work, 1-2 hours of OSS... Ofc, it varies a lot due to decent amount of traveling.

I read books ( you can check out what here - https://www.goodreads.com/user/show/61702968-krzysztof), spend time on photography (https://500px.com/krzysztofcieslak). I hike whenever I can (not often enough)... other than that, just normal things Netflix, friends, family.
